
import { HOME_PAGE_INDEX } from '@utils/constants/layout_constants';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Layout from '@components/layout/layout';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin']})

export default function Home() {
  return (
    <Layout childType={HOME_PAGE_INDEX}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        {/* Trending products*/}
        <div className="mt-1">
            <h3>Trending Items</h3>
        </div>
        {/* End of Trending Products */}

      </main>

    </Layout>
    );
};
